import './globals.css'
import '../styles/tailwind.css'
import { Inter } from 'next/font/google'
import {AuthProvider, } from '@/context/authContext'
import Navbar from '@/components/Navbar/IndexNavbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bussines Admin',  
  description: 'Generated by Timberli',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark:bg-neutral-950'>
        <body>
          <div className='dark:bg-neutral-950'>
          <AuthProvider>
            <Navbar fixed/>
            {children}
          </AuthProvider>
          </div>
        </body>
      </html>
  )
}
